### ISSUE TITLE
ndt matching is slow in comparison to ROS1.

### ISSUE THREAD

**Issue by rsasaki0109** [OUXT-Polaris/pcl_apps#7]
Hi, thanks for your hard work! 

I tried ndt matching using your code which I modified, but ndt matching in ROS2 was slow in comparison to ROS1 under the same conditions.

Following your team member's advice in [this article in Qiita](https://qiita.com/saitosasaki/items/ad34d6d31bdab43bf879), I recorded data in a profiler "perf" and analyzed it. But, it was difficult for me to find problems beacause I was inexperienced in the profiler.
Please advise me.

perf data
https://drive.google.com/file/d/14zyGaNY1rm1We0jARd8Q5l16AfVAyi9r/view?usp=sharing

screenshot(perf report)
![Screenshot from 2019-12-18 21-22-09](https://user-images.githubusercontent.com/18298605/71088824-c3d40900-21e2-11ea-9e11-4d2a5f292b1d.png)

the code I modified 
https://github.com/rsasaki0109/pcl_apps

**Comment by hakuturu583** [comment]
Can you show me the parameters in NDT matching component?

**Comment by rsasaki0109** [comment]
The parameters when recording are as follows.
https://github.com/rsasaki0109/pcl_apps/blob/master/pcl_apps/param/mapping.yaml
・NormalDistributionsTransform
    transform_epsilon: 0.1
    step_size: 0.1 
    resolution: 5.0 
    max_iterations: 25
・VoxelGrid
    voxel_leaf_size: 2.5

**Comment by hakuturu583** [comment]
Hunn... It seems the parameter is valid...

**Comment by rsasaki0109** [comment]
Hello!
I viewed codes for the first time in a while,so I found optimization options in CMakeLists.txt!

https://github.com/rsasaki0109/pcl_apps/blob/master/pcl_apps/CMakeLists.txt#L19

Sorry for the creless mistake😅
